"""add_notifications_table

Revision ID: 480f316c4bfc
Revises: 9b3a4f7c2d5e
Create Date: 2026-07-16 01:12:48.799119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '480f316c4bfc'
down_revision: Union[str, Sequence[str], None] = '9b3a4f7c2d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, confirmed, cancelled, completed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_appointments_client_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_seller_id'), table_name='appointments')
    op.alter_column('availability_overrides', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('availability_overrides', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('availability_overrides', 'is_available',
               existing_type=sa.BOOLEAN(),
               comment='false=blocked, true=extra available',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_availability_overrides_date'), table_name='availability_overrides')
    op.drop_index(op.f('ix_availability_overrides_user_id'), table_name='availability_overrides')
    op.alter_column('availability_templates', 'day_of_week',
               existing_type=sa.INTEGER(),
               comment='0=Sunday, 1=Monday, ..., 6=Saturday',
               existing_nullable=False)
    op.drop_index(op.f('ix_availability_templates_user_id'), table_name='availability_templates')
    op.alter_column('products', 'store_location_id',
               existing_type=sa.UUID(),
               comment='Sucursal donde se ofrece este producto',
               existing_nullable=True)
    op.alter_column('services', 'store_location_id',
               existing_type=sa.UUID(),
               comment='Sucursal donde se ofrece este servicio',
               existing_nullable=True)
    op.drop_index(op.f('ix_store_locations_user_id'), table_name='store_locations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_store_locations_user_id'), 'store_locations', ['user_id'], unique=False)
    op.alter_column('services', 'store_location_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Sucursal donde se ofrece este servicio',
               existing_nullable=True)
    op.alter_column('products', 'store_location_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Sucursal donde se ofrece este producto',
               existing_nullable=True)
    op.create_index(op.f('ix_availability_templates_user_id'), 'availability_templates', ['user_id'], unique=False)
    op.alter_column('availability_templates', 'day_of_week',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='0=Sunday, 1=Monday, ..., 6=Saturday',
               existing_nullable=False)
    op.create_index(op.f('ix_availability_overrides_user_id'), 'availability_overrides', ['user_id'], unique=False)
    op.create_index(op.f('ix_availability_overrides_date'), 'availability_overrides', ['date'], unique=False)
    op.alter_column('availability_overrides', 'is_available',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='false=blocked, true=extra available',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('availability_overrides', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('availability_overrides', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.create_index(op.f('ix_appointments_seller_id'), 'appointments', ['seller_id'], unique=False)
    op.create_index(op.f('ix_appointments_date'), 'appointments', ['date'], unique=False)
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, confirmed, cancelled, completed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
