"""social_admin

Revision ID: 605e383c7ffa
Revises: f91ad281fa21
Create Date: 2026-07-09 23:38:20.551799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = '605e383c7ffa'
down_revision: Union[str, Sequence[str], None] = 'f91ad281fa21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_app_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform_group', sa.String(length=20), nullable=False),
    sa.Column('app_id', sa.String(length=255), nullable=False),
    sa.Column('app_secret', app.modules.social.models.EncryptedString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('social_accounts', sa.Column('last_modified_by', sa.UUID(), nullable=True))
    op.add_column('social_accounts', sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'social_accounts', 'users', ['last_modified_by'], ['id'], ondelete='SET NULL')
    op.add_column('social_tokens', sa.Column('last_modified_by', sa.UUID(), nullable=True))
    op.add_column('social_tokens', sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'social_tokens', 'users', ['last_modified_by'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_staff')
    op.drop_constraint(None, 'social_tokens', type_='foreignkey')
    op.drop_column('social_tokens', 'last_modified_at')
    op.drop_column('social_tokens', 'last_modified_by')
    op.drop_constraint(None, 'social_accounts', type_='foreignkey')
    op.drop_column('social_accounts', 'last_modified_at')
    op.drop_column('social_accounts', 'last_modified_by')
    op.drop_table('social_app_credentials')
    # ### end Alembic commands ###
