"""add_media_and_edited_fields_to_wall

Revision ID: 880556632e90
Revises: ad3dea62b861
Create Date: 2026-05-10 17:40:42.410350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880556632e90'
down_revision: Union[str, Sequence[str], None] = 'ad3dea62b861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('media_url', sa.String(length=255), nullable=True))
    op.add_column('comments', sa.Column('media_type', sa.String(length=50), nullable=True))
    op.add_column('comments', sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('posts', sa.Column('media_url', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('media_type', sa.String(length=50), nullable=True))
    op.add_column('posts', sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_edited')
    op.drop_column('posts', 'media_type')
    op.drop_column('posts', 'media_url')
    op.drop_column('comments', 'is_edited')
    op.drop_column('comments', 'media_type')
    op.drop_column('comments', 'media_url')
    # ### end Alembic commands ###
