"""Add location table and relations

Revision ID: aaa96a5d6d50
Revises: c67ad7e81f0c
Create Date: 2026-07-07 00:33:27.536402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa96a5d6d50'
down_revision: Union[str, Sequence[str], None] = 'c67ad7e81f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('country', sa.String(length=100), nullable=True),
        sa.Column('country_code', sa.String(length=10), nullable=True),
        sa.Column('state', sa.String(length=100), nullable=True),
        sa.Column('state_code', sa.String(length=10), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('neighborhood', sa.String(length=150), nullable=True),
        sa.Column('address', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('customers', sa.Column('location_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'customers', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'country_code')
    op.drop_column('customers', 'address')
    op.drop_column('customers', 'department')
    op.add_column('users', sa.Column('location_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    op.drop_column('users', 'country')
    op.drop_column('users', 'neighborhood')
    op.drop_column('users', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('neighborhood', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'location_id')
    op.add_column('customers', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('country_code', sa.CHAR(length=2), server_default=sa.text("'CO'::bpchar"), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'location_id')
    op.drop_table('locations')
    # ### end Alembic commands ###
