"""Add is_ai_generated to social_posts

Revision ID: e620255f43e9
Revises: 0d7651c127d9
Create Date: 2026-07-09 21:19:48.223330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e620255f43e9'
down_revision: Union[str, Sequence[str], None] = '0d7651c127d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_posts', sa.Column('is_ai_generated', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_posts', 'is_ai_generated')
    # ### end Alembic commands ###
