"""Add social module tables

Revision ID: f91ad281fa21
Revises: e8f4a2b91c3d
Create Date: 2026-07-08 22:21:35.141039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f91ad281fa21'
down_revision: Union[str, Sequence[str], None] = 'e8f4a2b91c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_accounts', 'expires_at')
    op.drop_column('social_accounts', 'refresh_token')
    op.drop_column('social_accounts', 'access_token')
    op.drop_constraint(op.f('social_posts_user_id_fkey'), 'social_posts', type_='foreignkey')
    op.create_foreign_key(None, 'social_posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_posts', type_='foreignkey')
    op.create_foreign_key(op.f('social_posts_user_id_fkey'), 'social_posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('social_accounts', sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('social_accounts', sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('social_accounts', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
